apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: website
stringData:
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@postgres:5432/%s" .Values.postgres.auth.username .Values.postgres.auth.password .Values.postgres.auth.database | quote }}